// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// matrixmultiplicationC
SEXP matrixmultiplicationC(const Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _ELLsae_matrixmultiplicationC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixmultiplicationC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// rowmeanC
NumericVector rowmeanC(NumericMatrix x);
RcppExport SEXP _ELLsae_rowmeanC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rowmeanC(x));
    return rcpp_result_gen;
END_RCPP
}
// rddrawmatrixC
NumericMatrix rddrawmatrixC(int num_unique_elements, int n_bootstrap, NumericVector elements_to_draw_from, int n_obs_censusdata);
RcppExport SEXP _ELLsae_rddrawmatrixC(SEXP num_unique_elementsSEXP, SEXP n_bootstrapSEXP, SEXP elements_to_draw_fromSEXP, SEXP n_obs_censusdataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num_unique_elements(num_unique_elementsSEXP);
    Rcpp::traits::input_parameter< int >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type elements_to_draw_from(elements_to_draw_fromSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs_censusdata(n_obs_censusdataSEXP);
    rcpp_result_gen = Rcpp::wrap(rddrawmatrixC(num_unique_elements, n_bootstrap, elements_to_draw_from, n_obs_censusdata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ELLsae_matrixmultiplicationC", (DL_FUNC) &_ELLsae_matrixmultiplicationC, 2},
    {"_ELLsae_rowmeanC", (DL_FUNC) &_ELLsae_rowmeanC, 1},
    {"_ELLsae_rddrawmatrixC", (DL_FUNC) &_ELLsae_rddrawmatrixC, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ELLsae(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
