#' @title generateSAEdata
#' @description Provides example data for ELLsea functions and returns 
#' a survey and census dataset
#' @describeIn Provides example data for ELLsea functions and returns 
#' a survey and census dataset
#' @param nObs number of observations per area
#' @param nAreas the number of areas, default is 100
#' @param betas vector of three containing betas for the estimation of the response
#' @param fraction split between survey and census data (between 0 and 1)
#' @return Generates a list containing random \code{surveydata} and random \code{censusdata}. The variables
#' \code{x1, x2} are generated from bernoulli distribitions and \code{x2} is generated by a poisson distribution
#' with lambda equal to the location. Next to an individual error a nested error is used to create the response.
#' @export
#' @references 
#'  Guadarrama Sanz, M., Molina, I., and Rao, J.N.K.  (2016). \emph{A comparison of small 
#'  area estimation methods for poverty mapping}. In: 17 (Mar. 2016), 41-66 and 156 and 158.
#' 

generateSAEdata <- function(nObs =30, nAreas = 50, betas = c(25, -0.029, 45.5), fraction = 0.2){
  ntotal <- nObs*nAreas
  x1 <- rep(NA, ntotal)
  po <- 0
  for (i in 1:nAreas) {
    for(g in 1:nObs){
      po <- po+1
    x1[po] <- rbinom(n=1, size=1, prob = (0.25+(0.5*i))/nAreas)
  }}
  x2 <- rbinom(n=ntotal, size=1, prob = 0.3)
  location <- rep(1:nAreas, each = nObs)
  x3 <- rep(NA, ntotal)
  for (i in 1:ntotal) {
    x3[i] <- rpois(n=1, lambda=location[i])
  }
  
  # create response with nested error
  explMatrix <- as.matrix(data.frame(x1, x2, x3))
  y <- (explMatrix %*% betas + 
          rnorm(n= ntotal, mean=0, sd=0.14) + 
          rep(rnorm(n=nAreas, mean = 0, sd=0.6), each = nObs))
  
  rdata <- data.frame(y, x1, x2, x3, location)
  
  # generate indexes for the rows to keep. order indexes to keep. 
  helper <- sample(x = 1:nrow(rdata), size = nrow(rdata)*fraction, replace = F)
  helper <- sort(helper)
  
  #create training and test set from the originial data set using the indexes
  surveydata <- rdata[helper,]
  censusdata <- rdata[-helper,]
  return(list(surveydata, censusdata))
}