# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rowmeanC <- function(x) {
    .Call(`_ELLsae_rowmeanC`, x)
}

inferenceCensusC <- function(n_bootstrap, n_obs_censusdata, locationeffects, residuals, X, beta_sample) {
    .Call(`_ELLsae_inferenceCensusC`, n_bootstrap, n_obs_censusdata, locationeffects, residuals, X, beta_sample)
}

rowmeansBigC <- function(fbm) {
    .Call(`_ELLsae_rowmeansBigC`, fbm)
}

